# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .rpm/git-manager.spec
release_suffix: "{PACKIT_PROJECT_VERSION}"

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: git-manager
# downstream (Fedora) RPM package name
downstream_package_name: git-manager

actions:
  create-archive:
    - bash -c "V=$(grep -m1 '^Version:' .rpm/git-manager.spec | awk '{print $2}' | tr -d '\r'); make dist VERSION=$V"
    - bash -c 'ls -1t git-manager-*.tar.gz | head -n1'

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-44-aarch64
      - fedora-44-x86_64

  - <<: *copr
    trigger: release
    owner: 'odilhao'
    project: git-manager



srpm_build_deps:
  - golang
  - make
