# Generated by go2rpm 1.19.0
%bcond check 1

%define goipath         github.com/Odilhao/git-manager


Name:           golang-github-odilhao-git-manager
Version:        0.0.1
Release:        %autorelease
Summary:        None

License:        MIT
URL:            https://github.com/Odilhao/git-manager
Source0:        https://github.com/Odilhao/git-manager/archive/refs/tags/%{version}.tar.gz#/%{name}-%{version}.tar.gz

BuildRequires:  golang
BuildRequires:  go-rpm-macros
BuildRequires:  git-core
Requires:       git-core

%description
# FIXME

%prep
%setup -q -n git-manager-%{version}

%build
mkdir -p _gopath/src/github.com/Odilhao _build/bin
ln -s "$(pwd)" _gopath/src/github.com/Odilhao/git-manager
export GOPATH=$(pwd)/_gopath
export GO111MODULE=on
for cmd in cmd/* ; do
  go build -o _build/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
install -m 0755 -vd %{buildroot}%{_bindir}
install -m 0755 -vp _build/bin/git-manager %{buildroot}%{_bindir}/

%check
%if %{with check}
export GOPATH=$(pwd)/_gopath
export GO111MODULE=on
go test -v ./...
%endif

%files
%license LICENSE
%doc docs templates/README.md templates/completions/README.md
%{_bindir}/git-manager


%changelog
%autochangelog
