# Generated by go2rpm 1.19.0
%bcond check 1

%global goipath         github.com/Odilhao/git-manager

%gometa -L -f


Name:           golang-github-odilhao-git-manager
Version:        0
Release:        %autorelease -p
Summary:        None

# Generated by go-vendor-tools
License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
BuildRequires:  go-rpm-macros

%description
# FIXME

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc docs templates/README.md templates/completions/README.md
%{_bindir}/git-manager


%changelog
%autochangelog
